build:
  version: 2016-02-13 #version 
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /usr/local/go/src/github.com/cloud66/starter/starter:./artifacts/starter
    tester:
      name: tester
      depends_on: 
        - builder
      dockerfile: Dockerfile.tester
      command: go test
    crosscompile:
      name: crosscompile
      depends_on: 
        - tester
      dockerfile: Dockerfile.crosscompile
      artifacts:
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_darwin_386:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_darwin_amd64:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_windows_386.exe:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_windows_amd64.exe:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_linux_386:./artifacts/compiled
        - /usr/local/go/src/github.com/cloud66/starter/compiled/starter_linux_amd64:./artifacts/compiled
        
      
